import type { Metadata } from "next";
//funzione di Next.js per ottimizzare i font (usare questo invece che usare direttamente @font-face)
import localFont from "next/font/local";
import "./globals.css";

const clashNormal = localFont({
  src: [
    {
      path: "./../public/fonts/SCmagic.ttf",
      weight: "400",
    },
  ],
  variable: "--font-clashNormal",
});

const clashSmall = localFont({
  src: [
    {
      path: "./../public/fonts/blogger.ttf",
      weight: "400",
    },
  ],
  variable: "--font-clashSmall",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${clashNormal.variable} ${clashSmall.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
